name: dtvc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.1.0=py39hb82d6ee_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - ca-certificates=2020.10.14=0
  - certifi=2021.10.8=py39hcbf5309_1
  - cffi=1.15.0=py39h0878f49_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.10.0=py_2
  - debugpy=1.4.1=py39h415ef7b_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - et_xmlfile=1.0.1=py_1001
  - freetype=2.10.4=h546665d_1
  - icu=68.2=h0e60522_0
  - importlib-metadata=4.8.2=py39hcbf5309_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h57928b3_3556
  - ipykernel=6.4.2=py39h832f523_0
  - ipython=7.28.0=py39h832f523_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.0=py39hcbf5309_2
  - jpeg=9d=h8ffe710_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hcbf5309_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.2=py39h2e07f2f_0
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - libdeflate=1.8=h8ffe710_0
  - liblapack=3.9.0=12_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.3.0=hd413186_2
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - markupsafe=2.0.1=py39hb82d6ee_1
  - matplotlib=3.4.3=py39hcbf5309_1
  - matplotlib-base=3.4.3=py39h581301d_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39hb82d6ee_1005
  - mkl=2021.4.0=h0e2418a_729
  - nbclient=0.5.8=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hcbf5309_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.5=pyha770c72_0
  - numpy=1.21.3=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1l=h8ffe710_0
  - pandas=1.3.4=py39h2e25243_0
  - pandoc=2.16.1=h8ffe710_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39h916092e_0
  - pip=21.3.1=pyhd8ed1ab_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.21=pyha770c72_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - pyrsistent=0.18.0=py39hb82d6ee_0
  - python=3.9.7=h7840368_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.3=pyhd8ed1ab_0
  - pywin32=301=py39hb82d6ee_0
  - pywinpty=1.1.5=py39h99910a6_1
  - pyzmq=22.3.0=py39he46f08e_0
  - qt=5.12.9=h5909a2a_4
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.2.0=py39hcbf5309_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h8ffe710_2
  - tbb=2021.4.0=h2d74725_0
  - terminado=0.12.1=py39hcbf5309_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h8ffe710_1
  - tornado=6.1=py39hb82d6ee_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - tzdata=2021e=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.0=h6255e5f_0
  - pip:
    - absl-py==1.0.0
    - anyio==3.6.2
    - astunparse==1.6.3
    - automat==20.2.0
    - beautifulsoup4==4.10.0
    - bioinfokit==0.6
    - blis==0.7.5
    - bs4==0.0.1
    - cachetools==5.0.0
    - catalogue==2.0.6
    - charset-normalizer==2.0.7
    - click==7.1.2
    - constantly==15.1.0
    - cryptography==35.0.0
    - cssselect==1.1.0
    - cymem==2.0.6
    - cython==0.29.23
    - echarts-china-cities-pypkg==0.0.9
    - en-core-web-sm==3.0.0
    - et-xmlfile==1.1.0
    - filelock==3.6.0
    - flask==2.0.3
    - flatbuffers==1.12
    - funcy==1.16
    - future==0.18.2
    - gast==0.4.0
    - gensim==4.1.2
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - greenlet==2.0.2
    - grpcio==1.43.0
    - h11==0.12.0
    - h2==3.2.0
    - h5py==3.6.0
    - hpack==3.0.0
    - huggingface-hub==0.5.1
    - hyperframe==5.2.0
    - hyperlink==21.0.0
    - idna==3.3
    - imageio==2.16.1
    - imbalanced-learn==0.9.0
    - imblearn==0.0
    - incremental==21.3.0
    - ipywidgets==7.7.0
    - itemadapter==0.4.0
    - itemloaders==1.0.4
    - itsdangerous==2.1.2
    - jieba==0.42.1
    - jinja2==3.0.2
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonpath==0.82
    - jupyterlab-widgets==1.1.0
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - keras-tuner==1.1.0
    - kt-legacy==1.0.4
    - libclang==13.0.0
    - lml==0.1.0
    - lxml==4.6.4
    - markdown==3.3.6
    - matplotlib-venn==0.11.6
    - mdurl==0.1.2
    - murmurhash==1.0.6
    - networkx==2.7.1
    - nltk==3.6.5
    - numexpr==2.7.3
    - oauthlib==3.1.1
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - outcome==1.1.0
    - packaging==21.2
    - parsel==1.6.0
    - pathy==0.6.1
    - patsy==0.5.2
    - plotly==5.4.0
    - preshed==3.0.6
    - prettytable==3.6.0
    - priority==1.3.0
    - protego==0.2.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodome==3.17
    - pydantic==1.8.2
    - pydispatcher==2.0.5
    - pydot==1.4.2
    - pyecharts==2.0.3
    - pyecharts-jupyter-installer==0.0.3
    - pyexcelerator==0.6.4.1
    - pygal==3.0.0
    - pygal-maps-world==1.0.2
    - pygments==2.10.0
    - pyldavis==3.3.1
    - pyopenssl==21.0.0
    - pyparsing==2.4.7
    - python-graphviz==0.18.2
    - pytrends==4.7.3
    - pywavelets==1.3.0
    - pyyaml==6.0
    - queuelib==1.6.2
    - regex==2021.11.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-image==0.19.2
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - scrapy==2.5.1
    - seaborn==0.11.2
    - selenium==4.0.0
    - service-identity==21.1.0
    - simplejson==3.19.1
    - sklearn==0.0
    - smart-open==5.2.1
    - sniffio==1.2.0
    - snownlp==0.12.3
    - sortedcontainers==2.4.0
    - soupsieve==2.2.1
    - spacy==3.0.7
    - spacy-legacy==3.0.8
    - sqlalchemy==2.0.7
    - squarify==0.4.3
    - srsly==2.4.2
    - starlette==0.26.1
    - statsmodels==0.13.0
    - tabulate==0.8.9
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.8.0
    - tensorflow-addons==0.16.1
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - textblob==0.17.1
    - textwrap3==0.9.2
    - tf-estimator-nightly==2.8.0.dev2021122109
    - thinc==8.0.12
    - threadpoolctl==3.0.0
    - tifffile==2022.3.16
    - tokenizers==0.11.6
    - tqdm==4.62.3
    - transformers==4.18.0
    - trio==0.19.0
    - trio-websocket==0.9.2
    - tweepy==4.2.0
    - twisted==22.1.0
    - twisted-iocpsupport==1.0.2
    - typeguard==2.13.3
    - typer==0.3.2
    - typing-extensions==4.5.0
    - urllib3==1.26.7
    - w3lib==1.22.0
    - wasabi==0.8.2
    - webdriver-manager==3.5.4
    - werkzeug==2.0.3
    - widgetsnbextension==3.6.0
    - workbook==1.1
    - wrapt==1.13.3
    - wsproto==1.0.0
    - xlrd==2.0.1
    - xlutils==2.0.0
    - xlwt==1.3.0
    - xxhash==3.2.0
    - zope-interface==5.4.0
prefix: D:\py-anaconda\envs\dtvc
